{% set name = "crystmatch" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crystmatch-{{ version }}.tar.gz
  sha256: 676b6649e1c392c8ed93df379da8664c115cd0249ac2598e4ae899782b9ede6b

build:
  entry_points:
    - crystmatch = crystmatch:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - spglib
    - numba
    - tqdm

test:
  imports:
    - crystmatch
  commands:
    - pip check
    - crystmatch --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Fangcheng-Wang/crystmatch
  summary: Enumerating and analyzing crystal-structure matches for solid-solid phase transitions.
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - THIRD_PARTY_LICENSES

extra:
  recipe-maintainers:
    - Fangcheng-Wang
