{% set name = "crystmatch" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crystmatch-{{ version }}.tar.gz
  sha256: ec327b2be640c74c2fee5069c32379f84b7f274cbab9ce67852937309050e1db

build:
  entry_points:
    - crystmatch = crystmatch:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - spglib
    - tqdm

test:
  imports:
    - crystmatch
  commands:
    - pip check
    - crystmatch --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Fangcheng-Wang/crystmatch
  summary: Enumerating and analyzing crystal-structure matches for solid-solid phase transitions.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fangcheng-Wang
